import React, { useEffect, useState } from 'react';
import axios from 'axios';
import './styles.css';
interface Email { id:number; from:string; to:string; subject:string; body:string; aiCategory?:string; createdAt:string; }
export default function App(){ const [emails,setEmails]=useState<Email[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(false);
const [accountFilter,setAccountFilter]=useState(''); const [folderFilter,setFolderFilter]=useState('');
const load = async ()=>{ setLoading(true); try{ const params=new URLSearchParams(); if(q)params.append('q',q); if(accountFilter)params.append('account',accountFilter); if(folderFilter)params.append('folder',folderFilter); const res=await axios.get(`http://localhost:4000/search/emails?${params.toString()}`); setEmails(res.data.hits||[]); }catch(e){ console.error(e); alert('Error fetching emails. Is backend running on http://localhost:4000 ?'); } finally{ setLoading(false); } };
useEffect(()=>{ load(); }, []);
return (<div className='app'><header className='topbar'><h1>ReachInbox — Onebox</h1><div className='controls'><input className='search' placeholder='Search subject, from, body...' value={q} onChange={e=>setQ(e.target.value)}/><input className='filter' placeholder='Account' value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}/><input className='filter' placeholder='Folder' value={folderFilter} onChange={e=>setFolderFilter(e.target.value)}/><button className='btn' onClick={load}>Search</button></div></header><main className='main'>{loading? <div className='status'>Loading...</div>:null}<div className='email-list'>{emails.length===0? <div className='empty'>No emails yet — wait for mock arrivals or connect IMAP.</div>:null}{emails.map(e=> (<article key={e.id} className={'email-card '+(e.aiCategory==='Interested'?'interested':'')}> <div className='meta'><div className='from'>{e.from}</div><div className='subject'>{e.subject}</div><div className='category'>{e.aiCategory||'—'}</div></div><div className='body'>{e.body}</div><div className='actions'><button className='btn small' onClick={async ()=>{ try{ const r=await axios.get(`http://localhost:4000/api/replies/${e.id}/suggest`); alert('Suggested reply:\n\n'+(r.data.suggestion||'No suggestion')); }catch(err){ alert('Error fetching suggestion'); } }}>Suggest Reply</button></div></article>))}</div></main><footer className='footer'>Demo mode — mock IMAP when USE_MOCK=true. For full features set .env and run Prisma + MySQL.</footer></div>); }
